version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && npm install && tail -F anything"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - 'db'
volumes:
  db: