version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:create && bin/rails db:migrate && bin/foreman start -f Procfile.dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - 'db'